apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  tag: "1.27.0"
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    defaultConfig:
      tracingServiceName: CANONICAL_NAME_ONLY
      tracing:
        sampling: 50
    extensionProviders:
    - name: otel-access-log
      envoyOtelAls:
        service: opentelemetry-deployment-collector.observability.svc.cluster.local
        port: 4317
        logFormat:
          labels:
            cluster: "%ENVIRONMENT(ISTIO_META_CLUSTER_ID)%"
            mesh: "%ENVIRONMENT(ISTIO_META_MESH_ID)%"
            protocol: "%PROTOCOL%"
            method: "%REQ(:METHOD)%"
            path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            status: "%RESPONSE_CODE%"
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: opentelemetry-deployment-collector.observability.svc.cluster.local
        resource_detectors:
          environment: {}
    defaultProviders:
      accessLogging:
      - otel-access-log
      metrics:
      - prometheus
      tracing:
      - otel-tracing

    # extensionProviders:
    # defaultProviders:
    #   accessLogging:
    #   - envoy
    #   - otel
