apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  tag: "1.27.0"
  meshConfig:
    accessLogFile: /dev/stdout
    # accessLogFormat: |
    #   [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME% traceID=%REQ(x-b3-traceid)%
    # enableTracing: true
    # defaultConfig:
    #   tracing:
    #     sampling: 100
    #     max_path_tag_length: 99999
    #     zipkin:
    #       address: otel-collector.tracing.svc:9411
    
    # extensionProviders:
    # - name: otel
    #   envoyOtelAls:
    #     service: application-opentelemetry-collector.observability.svc.cluster.local
    #     port: 4317
    #     logFormat:
    #       labels:
    #         pod: "%ENVIRONMENT(POD_NAME)%"
    #         namespace: "%ENVIRONMENT(POD_NAMESPACE)%"
    #         cluster: "%ENVIRONMENT(ISTIO_META_CLUSTER_ID)%"
    #         mesh: "%ENVIRONMENT(ISTIO_META_MESH_ID)%"
    #         workload: "%ENVIRONMENT(ISTIO_META_WORKLOAD_NAME)%"
    #         protocol: "%PROTOCOL%"
    #         method: "%REQ(:METHOD)%"
    #         path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
    #         status: "%RESPONSE_CODE%"
    # defaultProviders:
    #   accessLogging:
    #   - envoy
    #   - otel
