apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: minimal
  tag: "1.27.0"
  meshConfig:
    accessLogFile: /dev/stdout
    extensionProviders:
    - name: otel
      envoyOtelAls:
        service: application-opentelemetry-collector.observability.svc.cluster.local
        port: 4317
        logFormat:
          labels:
            workload: "%ENVIRONMENT(ISTIO_META_WORKLOAD_NAME)%"
            pod: "%ENVIRONMENT(POD_NAME)%"
            namespace: "%ENVIRONMENT(POD_NAMESPACE)%"
            cluster: "%ENVIRONMENT(ISTIO_META_CLUSTER_ID)%"
            mesh: "%ENVIRONMENT(ISTIO_META_MESH_ID)%"
            status: "%RESPONSE_CODE%"
            message: "%LOCAL_REPLY_BODY%"
            protocol: "%PROTOCOL%"
    defaultProviders:
      accessLogging:
      - envoy
      - otel
